- name: Playbook 1
  hosts: localhost
  tasks:
    - name: TASK 1
      ansible.builtin.debug:
        msg: "Hello from Play 1 and Task22"

- name: Playbook 2
  hosts: localhost
  tasks:
    - name: TASK 2
      ansible.builtin.debug:
        msg: "Hello from Play 2 and Task 22"