- name: Variable from TASK
  hosts: localhost
  vars:
    course: "AWS"
    Trainer: "Prem"
    Duration: "120 Hrs"
  tasks: 
    - name: Variable from TASK
      vars:
        course: "AWS"
        Trainer: "Trixie"
        Duration: "6 months"
      ansible.builtin.debug:
        msg: "Hi, I'm learning {{course}}, Trainer is {{Trainer}} and duration is {{Duration}}"