- name: Variable from TASK
  hosts: localhost
  vars_files:
    variables.yaml
  tasks: 
    - name: Variable from TASK
      ansible.builtin.debug:
        msg: "Hi, I'm learning {{course}}, Trainer is {{Trainer}} and duration is {{Duration}}"