- name: Variable from Prompt
  hosts: localhost
  vars_prompt:
  - course: course
  - Trainer: Trainer
  - Duration: Duration
  tasks: 
    - name: Variable from Prompt
      ansible.builtin.debug:
        msg: "Hi, I'm learning {{course}}, Trainer is {{Trainer}} and duration is {{Duration}}"