- name: Checking variable Preferences
  hosts: localhost
  # vars_files:
  #  - variables.yaml
  # vars_prompt:
  #   - name: person 
  #     prompt: please enter your name
  #     private: false
  #   - name: wishes 
  #     prompt: Please enter the wish 
  #     private: false 
  # vars:
  #   person: "Prem from PLAY"
  #   wishes: "Morning from Play"
  tasks: 
    - name: Checking variable Preferences
      # vars:
      #   person: "Prem from TASK"
      #   wishes: "Morning from TASK"
      ansible.builtin.debug:
        msg: "Hi, {{person}}, Good {{wishes}}"

# - from Command Line (Arguments)
# - from Task level
# - from -var_files
# - from Prompt 
# - from PLAY level 
# - from Inventory level






