- name: Loops
  hosts: localhost 
  tasks: 
    - name: loop 
      ansible.builtin.debug:
        msg: "Hello {{item}}" #Iteam is the default key-word 
      loop:
        - Prem
        - Trixie
        - Sumathi