- name: ping playbook
  become: yes
  hosts: web
  tasks:
    - name: ping the server
      ansible.builtin.ping:

    - name: Installing Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Starting Nginx
      ansible.builtin.service:
        name: nginx
        state: started
